use_frameworks!
platform :ios, '12.0'

target 'MyRepoForLab_Example' do
  pod 'MyRepoForLab', :path => '../'

  target 'MyRepoForLab_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
